In [1]:
import requests
import pandas as pd

BASE_URL = "https://www.cheapshark.com/api/1.0/deals"

# CheapShark rejects requests that send a generic User-Agent (the default
# "python-requests/x.y" now returns HTTP 400), so identify this client explicitly.
HEADERS = {
    "User-Agent": "steam-deals-final-project/1.0 (github.com/hykatbia/foundations-final-project)"
}

def fetch_all_deals(store_id="1", page_size=60, max_pages=30):
    """
    Fetch multiple pages of CheapShark deals.

    - store_id="1" means Steam
    - page_size=60 is the maximum number of deals per page
    - max_pages is a safety limit so we don't loop forever
    """
    all_deals = []
    page = 0

    while page < max_pages:
        params = {
            "storeID": store_id,
            "pageSize": page_size,
            "pageNumber": page,
            "sortBy": "Savings",  # sort by biggest discount first
        }
        print(f"Requesting page {page} ...")
        resp = requests.get(BASE_URL, params=params, headers=HEADERS, timeout=30)

        if resp.status_code != 200:
            # Print the API's own message so a failure is easy to diagnose
            print(f"  ❌ Status code {resp.status_code}, stopping.")
            print(f"     Response: {resp.text[:300]}")
            break

        deals = resp.json()

        # A good response is a list of deals. Anything else is an error object,
        # so stop here instead of letting pd.DataFrame() fail confusingly.
        if not isinstance(deals, list):
            print(f"  ❌ Unexpected response (not a list of deals): {deals}")
            break

        print(f"  Got {len(deals)} deals.")

        if not deals:
            # No more data, we've reached the end
            break

        all_deals.extend(deals)

        # If we got fewer than page_size deals, this is probably the last page
        if len(deals) < page_size:
            break

        page += 1

    print(f"\nTotal deals fetched: {len(all_deals)}")

    if not all_deals:
        # Fail loudly here rather than writing an empty CSV and breaking later cells
        raise RuntimeError(
            "No deals were fetched — see the error printed above. "
            "The later cells depend on this data, so stopping now."
        )

    df = pd.DataFrame(all_deals)

    # Convert CheapShark's releaseDate (Unix seconds) to datetime, year, and a readable date string
    if "releaseDate" in df.columns:
        df["release_date"] = pd.to_datetime(
            df["releaseDate"],
            unit="s",
            utc=True,
            errors="coerce"
        )
        df["release_year"] = df["release_date"].dt.year

        # 🔹 New column: formatted date string (e.g. 01/01/70, 10/04/16, etc.)
        df["date"] = df["release_date"].dt.strftime("%m/%d/%y")

    return df


df_raw = fetch_all_deals()
df_raw.head()

Requesting page 0 ...

  Got 60 deals.
Requesting page 1 ...

  Got 60 deals.
Requesting page 2 ...

  Got 60 deals.
Requesting page 3 ...

  Got 60 deals.
Requesting page 4 ...

  Got 60 deals.
Requesting page 5 ...

  Got 60 deals.
Requesting page 6 ...

  Got 60 deals.
Requesting page 7 ...

  Got 60 deals.
Requesting page 8 ...

  Got 60 deals.
Requesting page 9 ...

  Got 60 deals.
Requesting page 10 ...

  Got 60 deals.
Requesting page 11 ...

  Got 60 deals.
Requesting page 12 ...

  Got 60 deals.
Requesting page 13 ...

  Got 60 deals.
Requesting page 14 ...

  Got 60 deals.
Requesting page 15 ...

  Got 60 deals.
Requesting page 16 ...

  Got 60 deals.
Requesting page 17 ...

  Got 60 deals.
Requesting page 18 ...

  Got 60 deals.
Requesting page 19 ...

  Got 60 deals.
Requesting page 20 ...

  Got 60 deals.
Requesting page 21 ...

  Got 60 deals.
Requesting page 22 ...

  Got 60 deals.
Requesting page 23 ...

  Got 60 deals.
Requesting page 24 ...

  Got 60 deals.
Requesting page 25 ...

  Got 60 deals.
Requesting page 26 ...

  Got 60 deals.
Requesting page 27 ...

  Got 60 deals.
Requesting page 28 ...

  Got 60 deals.
Requesting page 29 ...

  Got 60 deals.

Total deals fetched: 1800

,internalName,title,metacriticLink,dealID,storeID,gameID,salePrice,normalPrice,isOnSale,savings,...,steamRatingPercent,steamRatingCount,steamAppID,releaseDate,lastChange,dealRating,thumb,release_date,release_year,date
0,MOONLIGHTER,Moonlighter,/game/moonlighter/,nxrnYZPQ%2FN2XroxyYO%2BYENVy02e6q79T49455V4OJ1...,1,187019,0.00,19.99,1,100.000000,...,80,7224,606150,1527552000,1785954211,10.0,https://shared.fastly.steamstatic.com/store_it...,2018-05-29 00:00:00+00:00,2018,05/29/18
1,BATTLEGROUNDSTHEPIRATEKING,Battlegrounds : The Pirate King,/game/battlegrounds-the-pirate-king/,t7M1ZDdKzF%2BSkOdzRi67TR5O17tjgjqDWwvugP82Umk%3D,1,324590,0.98,19.98,1,95.095095,...,0,0,2907650,1712880000,1785005278,2.3,https://shared.fastly.steamstatic.com/store_it...,2024-04-12 00:00:00+00:00,2024,04/12/24
2,THERITUAL,The Ritual,/game/the-ritual/,AvCnxTOk5ngiObKPItFepLIfQ92zTqFF6wThaN5AQEI%3D,1,327732,0.98,19.98,1,95.095095,...,0,0,3122100,1746144000,1785056698,2.8,https://shared.fastly.steamstatic.com/store_it...,2025-05-02 00:00:00+00:00,2025,05/02/25
3,ONECHANCE,One Chance,/game/one-chance/,29sAm0jDKGWCGMQ0VrByAb1uASyQ5riRe%2FwnjfK2xfA%3D,1,305060,0.99,19.99,1,95.047524,...,90,11,2862040,1716422400,1784835510,2.0,https://shared.fastly.steamstatic.com/store_it...,2024-05-23 00:00:00+00:00,2024,05/23/24
4,LUNATICTAXIDRIVER,Lunatic Taxi Driver,/game/lunatic-taxi-driver/,n03moVA1WOrD0jLkc5pFo4mED2yAXnOnbyw56c7VTM4%3D,1,305061,0.99,19.99,1,95.047524,...,85,14,2862030,1711238400,1784835534,2.0,https://shared.fastly.steamstatic.com/store_it...,2024-03-24 00:00:00+00:00,2024,03/24/24

In [2]:
df_raw.to_csv("cheapshark_updated.csv", index=False)

In [3]:
# Create a smaller table for the range/arrow plot: top 20 deals by dealRating
df_top20 = (
    df_raw.copy()
    .assign(dealRating_float=pd.to_numeric(df_raw["dealRating"], errors="coerce"))
    .sort_values("dealRating_float", ascending=False)
    .head(20)
)

# Keep only the columns needed for Datawrapper
df_top20_for_chart = df_top20[["title", "normalPrice", "salePrice", "release_year"]]

df_top20_for_chart.head()

,title,normalPrice,salePrice,release_year
0,Moonlighter,19.99,0.00,2018
369,Divinity: Original Sin - Enhanced Edition,39.99,3.99,2015
302,Cruelty Squad,19.99,1.99,2021
1589,Disco Elysium - The Final Cut,39.99,9.99,2021
182,LIMBO,12.49,1.24,2011

In [4]:
df_top20_for_chart.to_csv("steam_deals_top20_rangeplot.csv", index=False)