In [1]:
import requests
import pandas as pd

BASE_URL = "https://www.cheapshark.com/api/1.0/deals"

def fetch_all_deals(store_id="1", page_size=60, max_pages=30):
    """
    Fetch multiple pages of CheapShark deals.

    - store_id="1" means Steam
    - page_size=60 is the maximum number of deals per page
    - max_pages is a safety limit so we don't loop forever
    """
    all_deals = []
    page = 0

    while page < max_pages:
        params = {
            "storeID": store_id,
            "pageSize": page_size,
            "pageNumber": page,
            "sortBy": "Savings",  # sort by biggest discount first
        }
        print(f"Requesting page {page} ...")
        resp = requests.get(BASE_URL, params=params, timeout=30)

        if resp.status_code != 200:
            print(f"  ❌ Status code {resp.status_code}, stopping.")
            break

        deals = resp.json()
        print(f"  Got {len(deals)} deals.")

        if not deals:
            # No more data, we've reached the end
            break

        all_deals.extend(deals)

        # If we got fewer than page_size deals, this is probably the last page
        if len(deals) < page_size:
            break

        page += 1

    print(f"\nTotal deals fetched: {len(all_deals)}")

    df = pd.DataFrame(all_deals)

    # Convert CheapShark's releaseDate (Unix seconds) to datetime, year, and a readable date string
    if "releaseDate" in df.columns:
        df["release_date"] = pd.to_datetime(
            df["releaseDate"],
            unit="s",
            utc=True,
            errors="coerce"
        )
        df["release_year"] = df["release_date"].dt.year

        # 🔹 New column: formatted date string (e.g. 01/01/70, 10/04/16, etc.)
        df["date"] = df["release_date"].dt.strftime("%m/%d/%y")

    return df


df_raw = fetch_all_deals()
df_raw.head()

Requesting page 0 ...

  Got 60 deals.
Requesting page 1 ...

  Got 60 deals.
Requesting page 2 ...

  Got 60 deals.
Requesting page 3 ...

  Got 60 deals.
Requesting page 4 ...

  Got 60 deals.
Requesting page 5 ...

  Got 60 deals.
Requesting page 6 ...

  Got 60 deals.
Requesting page 7 ...

  Got 60 deals.
Requesting page 8 ...

  Got 60 deals.
Requesting page 9 ...

  Got 60 deals.
Requesting page 10 ...

  Got 60 deals.
Requesting page 11 ...

  Got 60 deals.
Requesting page 12 ...

  Got 60 deals.
Requesting page 13 ...

  Got 60 deals.
Requesting page 14 ...

  Got 60 deals.
Requesting page 15 ...

  Got 60 deals.
Requesting page 16 ...

  Got 60 deals.
Requesting page 17 ...

  Got 60 deals.
Requesting page 18 ...

  Got 60 deals.
Requesting page 19 ...

  Got 60 deals.
Requesting page 20 ...

  Got 60 deals.
Requesting page 21 ...

  Got 60 deals.
Requesting page 22 ...

  Got 60 deals.
Requesting page 23 ...

  Got 60 deals.
Requesting page 24 ...

  Got 60 deals.
Requesting page 25 ...

  Got 60 deals.
Requesting page 26 ...

  Got 60 deals.
Requesting page 27 ...

  Got 60 deals.
Requesting page 28 ...

  Got 60 deals.
Requesting page 29 ...

  Got 60 deals.

Total deals fetched: 1800

,internalName,title,metacriticLink,dealID,storeID,gameID,salePrice,normalPrice,isOnSale,savings,...,steamRatingPercent,steamRatingCount,steamAppID,releaseDate,lastChange,dealRating,thumb,release_date,release_year,date
0,GRAVITYCIRCUIT,Gravity Circuit,/game/gravity-circuit/,zmS4o0E%2FnDQY25xSFhqB6rQlds0CHQZre0%2BaYLkhU4...,1,267370,0.00,18.68,1,100.000000,...,95,2077,858710,1689206400,1780359502,10.0,https://shared.fastly.steamstatic.com/store_it...,2023-07-13 00:00:00+00:00,2023,07/13/23
1,ASWANGDETECTIVETHECASEOFNEWYORK,Aswang Detective: The Case of New York,/game/aswang-detective-the-case-of-new-york/,KcGZHBBKZc0%2BFSaAruWvMDi%2BstJzEqKCuiNbEihOKN...,1,323829,0.74,14.99,1,95.063376,...,0,0,2197170,1667952000,1780404149,0.8,https://shared.fastly.steamstatic.com/store_it...,2022-11-09 00:00:00+00:00,2022,11/09/22
2,VIAMORTIS,Via Mortis,/game/via-mortis/,zI4jnne1QoNw94B0SZb3R2rqWGs%2BACWrm%2B3mJbRNXD...,1,323830,0.74,14.99,1,95.063376,...,0,0,1987550,1652918400,1780404149,0.8,https://shared.fastly.steamstatic.com/store_it...,2022-05-19 00:00:00+00:00,2022,05/19/22
3,CASTLEFLIPPER,Castle Flipper,/game/pc/castle-flipper,Wqk8prvQbZmoBGUnWMPM7OL00j%2FX%2Ffp3%2B%2Fm6n4...,1,230223,0.94,18.99,1,95.050026,...,64,1017,944250,1621987200,1780341626,7.3,https://shared.fastly.steamstatic.com/store_it...,2021-05-26 00:00:00+00:00,2021,05/26/21
4,MYTHICALAGENT,Mythical Agent,/game/mythical-agent/,uBX%2FRmxUCBkhLibL5ANHVxTgtU%2FZotSRBdh3Fz%2F%...,1,323822,0.99,19.99,1,95.047524,...,0,0,2432630,1687737600,1780393496,3.4,https://shared.fastly.steamstatic.com/store_it...,2023-06-26 00:00:00+00:00,2023,06/26/23

In [2]:
df_raw.to_csv("cheapshark_updated.csv", index=False)

In [3]:
# Create a smaller table for the range/arrow plot: top 20 deals by dealRating
df_top20 = (
    df_raw.copy()
    .assign(dealRating_float=pd.to_numeric(df_raw["dealRating"], errors="coerce"))
    .sort_values("dealRating_float", ascending=False)
    .head(20)
)

# Keep only the columns needed for Datawrapper
df_top20_for_chart = df_top20[["title", "normalPrice", "salePrice", "release_year"]]

df_top20_for_chart.head()

,title,normalPrice,salePrice,release_year
0,Gravity Circuit,18.68,0.00,2023
1429,Last Man Sitting,9.99,2.49,2026
576,AI: THE SOMNIUM FILES - nirvanA Initiative,39.99,5.99,2022
160,LIMBO,12.49,1.24,2011
1042,Ori and the Blind Forest: Definitive Edition,19.99,3.99,2016

In [4]:
df_top20_for_chart.to_csv("steam_deals_top20_rangeplot.csv", index=False)